- src/main/resources/application-dev.yaml
- src/main/resources/application-prod.yaml
- src/main/resources/application.yaml
- dev, prod 프로필 분리 및 DB 연동 안됨 오류 수정했습니다.
---
- application.yaml에 .env 위치 명시 코드가 빠져있었습니다. 추가하여 DB 연결 테스트까지 확인 완료
- dev, prod 프로필 분리하였습니다. 
---
---
---
---
```
-Dspring.profiles.active=prod
-Dspring.profiles.active=dev
```
위에서 dev로 설정해서 지난 프로젝트에서 했던 것처럼 실행 구성 편집해주시면 됩니다
---
> Fix/profile-separate 스프링 프로필 dev, prod 분리

- docker-compose.dev.yml
- docker-compose.prod.yml
- start-dev.sh
- 스크립트 파일을 추가하여 소스코드를 변경했을 때 docker 통해 구동되는 웹사이트에 바로 반영될 수 있도록 하였습니다. (start-dev.sh)
- 로컬과 배포에 대해서 각각 docker-compose 파일을 분리했습니다.
---
- 프로젝트 루트 디렉토리에 start-dev.sh 추가하였습니다.
- docker-compose.dev.yml 추가
- docker-compose.prod.yml 추가
- env 파일을 도커 환경에서 참조할 수 있도록 추가
---
```
. /start-dev.sh
```
위 명령어 사용하면 빌드 및 도커 재구동까지 자동으로 됩니다! 꼭 확인해주세요!!!!
---
---
- Docker 구동 테스트
- 로그 문제 x
---
- 
---
> Chore/docker-separate 도커 운영, 개발환경 분리 및 스크립트 파일 추가

- src/main/java/_team/earnedit/EarneditApplication.java
- src/main/java/_team/earnedit/controller/EmailVerificationController.java
- src/main/java/_team/earnedit/controller/ProfileController.java
- src/main/java/_team/earnedit/dto/auth/EmailTokenVerifyRequestDto.java
- src/main/java/_team/earnedit/dto/profile/SalaryRequestDto.java
- src/main/java/_team/earnedit/dto/profile/SalaryResponseDto.java
- src/main/java/_team/earnedit/entity/Salary.java
- src/main/java/_team/earnedit/global/ErrorCode.java
- src/main/java/_team/earnedit/global/scheduler/AmountPerSecScheduler.java
- src/main/java/_team/earnedit/global/util/SalaryCalculator.java
- src/main/java/_team/earnedit/repository/SalaryRepository.java
- src/main/java/_team/earnedit/service/EmailVerificationService.java
- src/main/java/_team/earnedit/service/ProfileService.java
- 수익 정보 생성 api
- 초수익 스케줄러
- 이메일토큰검증에 토큰-이메일 검증 추가 @PlayTheApp 
---
- Salary 엔티티 정의
- 회의 내용 반영 : 컬럼명 amout 통일 및 월급일 컬럼(payday) 추가 -> 노션 반영 완
- profile 파일명으로 생성하여 구현 -> 수익 정보 처리는 프로필 영역
- 월마다 일수가 다르므로 스케줄러에서 초수익 계산값 업데이트
- 이메일토큰검증에 토큰-이메일 검증 추가
- 회의 내용 반영
---
> 수익 정보 생성 api
---
---
---
- 스웨거 붙여야함
---
> Feat/signup : 수익 정보 생성 api, 초수익 스케줄러, 이메일토큰검증에 토큰-이메일 검증 추가

- src/main/java/_team/earnedit/controller/WishController.java
- src/main/java/_team/earnedit/dto/wish/WishResponse.java
- src/main/java/_team/earnedit/global/ErrorCode.java
- src/main/java/_team/earnedit/global/exception/wish/WishException.java
- src/main/java/_team/earnedit/repository/WishRepository.java
- src/main/java/_team/earnedit/service/WishService.java
- 위시리스트 조회 API 추가
---
-  위시리스트 조회 API 추가
- WishException 추가 
---
> <img width="1199" height="1037" alt="image" src="https://github.com/user-attachments/assets/0f435e15-af27-4974-ad57-4dab0698aba2" />
- 정상적으로 조회
---
---
---
- 빠르게 기능 구현 초점으로 치고 있습니다
- 나중에 반드시 리팩토링 진행하겠지만, 문제 있는 부분은 그래도 지적 부탁드립니다~!
---
> Feat/wish-r 위시리스트 조회 API 

- src/main/java/_team/earnedit/controller/WishController.java
- src/main/java/_team/earnedit/dto/wish/WishUpdateRequest.java
- src/main/java/_team/earnedit/dto/wish/WishUpdateResponse.java
- src/main/java/_team/earnedit/entity/Wish.java
- src/main/java/_team/earnedit/global/ErrorCode.java
- src/main/java/_team/earnedit/service/WishService.java
- 위시 업데이트 API 추가
---
- 위시 업데이트 API 추가
---
> <img width="1422" height="1421" alt="image" src="https://github.com/user-attachments/assets/93117e33-957c-46bf-91d4-56f4717d40e3" />
- 위시 업데이트 API 테스트 성공
> <img width="1417" height="1309" alt="image" src="https://github.com/user-attachments/assets/5c3b6e1b-d412-4e64-81c5-5259a5ee4e52" />
- 이름 필드 공백일 시 예외 응답 정상처리. 그밖에 예외도 동일
---
---
---
---
> Feat/wish-u 위시 업데이트 API 

- src/main/java/_team/earnedit/controller/WishController.java
- src/main/java/_team/earnedit/global/ErrorCode.java
- src/main/java/_team/earnedit/service/WishService.java
- 삭제 API 추가
---
- 삭제 API 추가
---
> <img width="1426" height="1035" alt="image" src="https://github.com/user-attachments/assets/0bb3ee22-af21-4fd0-8ac4-c385d9e2cd24" />
- 삭제 성공
> <img width="1440" height="794" alt="image" src="https://github.com/user-attachments/assets/d95d1d8b-7dde-4d40-9d05-5fed2ad41045" />
- 이미 삭제된, 또는 존재하지 않는 위시 삭제 시도 시 예외 처리 
---
---
---
---
> Feat/wish-d 삭제 API 추가 

- src/main/java/_team/earnedit/controller/WishController.java
- src/main/java/_team/earnedit/service/WishService.java
- 위시 단일 조회 API 
---
- 위시 단일 조회 API 추가
---
> <img width="1464" height="992" alt="image" src="https://github.com/user-attachments/assets/bf7b2762-0839-48e8-ba89-ef7349cc35d0" />
- 성공 조회
> <img width="1535" height="1058" alt="image" src="https://github.com/user-attachments/assets/a6babf19-b403-48b0-a480-78211256697f" />
- 존재하지 않는 위시 조회 시도 시 예외
---
---
---
---
> Feat/wish-read-1 위시 단일 조회 API 

- src/main/java/_team/earnedit/controller/AuthController.java
- src/main/java/_team/earnedit/dto/auth/SignUpRequestDto.java
- src/main/java/_team/earnedit/dto/socialLogin/KakaoSignInRequestDto.java
- src/main/java/_team/earnedit/dto/socialLogin/KakaoUserInfoDto.java
- src/main/java/_team/earnedit/entity/User.java
- src/main/java/_team/earnedit/global/ErrorCode.java
- src/main/java/_team/earnedit/repository/UserRepository.java
- src/main/java/_team/earnedit/service/AuthService.java
- src/main/java/_team/earnedit/service/socialLogin/KakaoOAuthService.java
- 카카오 로그인 api 구현
---
- KakaoOAuthService 파일 생성
- 카카오 토큰에서 user info추출코드 구현
- signInWithKakao 서비스메서드 & 컨트롤러 메서드 구현
- email이 토큰에서 추출되지 않을 경우 kakaoId를 이용하여 생성해서 넣어줍니다
- 닉네임이 토큰에서 추출되지 않을 경우 다른 유저들과 똑같이 닉네임랜덤(but unique)생성으로 넣어줍니다
---
> FE에서 발급받은 kakao token으로 api 테스트
> DB에 잘 저장된 모습
---
---
---
- 소셜로그인 약관 관련 회의필요
---
> Feat/social login : 카카오 로그인 api 구현

- src/main/java/_team/earnedit/controller/StarController.java
- src/main/java/_team/earnedit/controller/WishController.java
- src/main/java/_team/earnedit/dto/wish/WishListResponse.java
- src/main/java/_team/earnedit/entity/Star.java
- src/main/java/_team/earnedit/entity/Wish.java
- src/main/java/_team/earnedit/global/ErrorCode.java
- src/main/java/_team/earnedit/global/exception/star/StarException.java
- src/main/java/_team/earnedit/repository/StarRepository.java
- src/main/java/_team/earnedit/repository/WishRepository.java
- src/main/java/_team/earnedit/service/StarService.java
- src/main/java/_team/earnedit/service/WishService.java
- Star 상태 업데이트 및 조회 API, 구매상태 업데이트 API 구현했습니다.
---
- Star 엔티티 추가
- Star 추가/삭제 (업데이트), 조회 API  추가
- 구매상태 업데이트 API 구현
---
> <img width="1426" height="859" alt="image" src="https://github.com/user-attachments/assets/d155aa74-2e8a-48d7-bfc8-9a87b0355605" />
- Wish의 Star 상태 변경 성공 
> <img width="1432" height="1021" alt="image" src="https://github.com/user-attachments/assets/3a89d835-f1a0-471d-8b99-715a3343cabe" />
- 유저의 Star 목록 조회
> <img width="1451" height="1097" alt="image" src="https://github.com/user-attachments/assets/7c77467d-8f59-4ab0-b093-155be39b7150" />
- Star 5개 초과 시 예외
> <img width="1400" height="938" alt="image" src="https://github.com/user-attachments/assets/58cb7310-53ea-4e86-9e15-3df12a1e2bbc" />
- 유저 Star 목록 조회 시 [] 값 예외 처리
> <img width="1446" height="790" alt="image" …
> Feat/star Star 상태 업데이트 API, 조회 API 구현

- build.gradle
- src/main/java/_team/earnedit/controller/AuthController.java
- src/main/java/_team/earnedit/dto/socialLogin/AppleSignInRequestDto.java
- src/main/java/_team/earnedit/dto/socialLogin/AppleUserInfoDto.java
- src/main/java/_team/earnedit/dto/socialLogin/KakaoUserInfoDto.java
- src/main/java/_team/earnedit/global/ErrorCode.java
- src/main/java/_team/earnedit/global/exception/OAuth/OAuthException.java
- src/main/java/_team/earnedit/global/jwt/ExternalJwtUtil.java
- src/main/java/_team/earnedit/service/AuthService.java
- src/main/java/_team/earnedit/service/socialLogin/AppleOAuthService.java
- src/main/java/_team/earnedit/service/socialLogin/KakaoOAuthService.java
- 애플 소셜로그인(회원가입) api 구현 (+ redis로 공개키 관리)
---
- build.gradle 에 필요 의존성 추가
- OAuthException 커스텀예외 파일 추가
- ExternalJwtUtil 클래스 생성
- 외부 서비스 전용 : RSA 공개 키 기반, 캐싱 필요
- AppleOAuthService 클래스 생성
- 애플 공개 키 기반 토큰 검증
- 서버요청 과다를 막기 위해 애플 공개 키는 redis로 관리 (12시간마다 재발급)
- 토큰에서 유저 정보 추출
- 애플 소셜로그인 api 구현
---
> 애플 소셜로그인 api
> DB
- 연속된 로그인 테스트 시 시간만 업데이트, 새로운 유저로 잘못생기는 에러 등 없습니다
---
---
---
---
> Feat/social apple : 애플 소셜로그인(회원가입) api 구현 (+ redis로 공개키 관리)

- src/main/java/_team/earnedit/controller/AuthController.java
- src/main/java/_team/earnedit/dto/auth/SignInResponseDto.java
- src/main/java/_team/earnedit/repository/TermRepository.java
- src/main/java/_team/earnedit/service/AuthService.java
- 로그인 response dto 변경
---
- 로그인 response dto 변경
- 분기처리를 hasAgreedTerm로 하기로 
---
> 바뀐 response
---
---
---
---
> Ref/response : 로그인 response dto 변경

- src/main/java/_team/earnedit/repository/UserRepository.java
- src/main/java/_team/earnedit/service/AuthService.java
- 자체로그인시 이메일 찾을 때 provider 같이 조회
---
- 바뀐 이메일 unique 조건에 맞춰서 자체로그인 로직 변경
---
> 포스트맨 요청 응답 스크린샷
---
---
---
---
> fix : 자체로그인시 이메일 찾을 때 provider 같이 조회

- src/main/java/_team/earnedit/controller/UserController.java
- src/main/java/_team/earnedit/entity/User.java
- src/main/java/_team/earnedit/global/ErrorCode.java
- src/main/java/_team/earnedit/global/scheduler/UserCleanupScheduler.java
- src/main/java/_team/earnedit/repository/UserRepository.java
- src/main/java/_team/earnedit/service/AuthService.java
- src/main/java/_team/earnedit/service/UserService.java
- 유저 탈퇴api, 탈퇴한 유저 복구로직, 탈퇴정책 로직 스케줄러 구현
---
⇒ 탈퇴 직후 기준 30일 이전 : 탈퇴한 이메일로 로그인 시도 시 → 이전 데이터 그대로 백업 (deleted → active)  /  탈퇴한 이메일로 회원가입 시도 시 → 중복된 이메일 예외
⇒ 탈퇴 직후 기준 30일 이후 : 탈퇴한 이메일로 재가입 시도 시 → **유저 입장에서는** 완전히 새 시작 (기존 탈퇴 회원의 email을 xxx@example.com_deleted_20250711 등으로 변경)
⇒ 탈퇴 직후 재가입 없이 3년 이후 : Hard delete (개인정보 보호법에 의거)
- 소셜 또한 모두 적용되었음
---
> 계정 삭제 (soft delete)
> 삭제된 계정으로 재로그인
---
---
---
- 로그아웃 구현과 함께 redis refresh 토큰 제거 구현 예정
---
> Feat/user delete : 유저 탈퇴api, 탈퇴한 유저 복구로직, 탈퇴정책 로직 스케줄러 구현

- src/main/java/_team/earnedit/controller/ProfileController.java
- src/main/java/_team/earnedit/entity/Salary.java
- src/main/java/_team/earnedit/service/ProfileService.java
- 1유저당 1 salary data로 수정(덮어쓰기로직), 수익조회 api 구현
---
- 1유저당 1 salary data로 수정
- 동일 api로 수익생성 & 수정 가능
- 수익조회 api 구현
---
> 수익 등록
> 수익 수정
> 수익 조회
---
---
---
---
> Feat/salary : 1유저당 1 salary data로 수정(덮어쓰기로직), 수익조회 api 구현

- src/main/java/_team/earnedit/service/MainService.java
- 사용자의 급여 정보 없을 때 예외 응답 제거
---
- SALARY_NOT_FOUND 예외 던지지 않도록 수정
- hasSalary 1 or 0 응답, 그 외의 데이터 (amount, payday 등) hasSalary 0 일때 0 값으로 응답하도록 수정
---
>  <img width="638" height="454" alt="image" src="https://github.com/user-attachments/assets/269dc87a-7a22-4f30-bf56-ce49bc7c468b" />
- 급여 정보 있을 때 응답 (hasSalary = true, 그 밖의 값 정상 출력)
> <img width="573" height="424" alt="image" src="https://github.com/user-attachments/assets/a94e9e1b-d9f1-4f0c-8647-c953b3c19482" />
- 급여 정보 없을 때 응답 (hasSalary = false, 그 밖의 값 0으로 처리)
---
---
- Swagger UI
---
- 준영님 요청으로 수정하였습니다.
---
> ref: SALARY_NOT_FOUND 예외처리 제거

- src/main/java/_team/earnedit/controller/DailyCheckController.java
- src/main/java/_team/earnedit/controller/PuzzleController.java
- src/main/java/_team/earnedit/dto/main/MainPageResponse.java
- src/main/java/_team/earnedit/dto/puzzle/PieceResponse.java
- src/main/java/_team/earnedit/dto/puzzle/PuzzleResponse.java
- src/main/java/_team/earnedit/entity/Item.java
- src/main/java/_team/earnedit/entity/Piece.java
- src/main/java/_team/earnedit/entity/PuzzleSlot.java
- src/main/java/_team/earnedit/entity/Rarity.java
- src/main/java/_team/earnedit/entity/Theme.java
- src/main/java/_team/earnedit/global/ErrorCode.java
- src/main/java/_team/earnedit/global/exception/item/ItemException.java
- src/main/java/_team/earnedit/global/exception/piece/PieceException.java
- src/main/java/_team/earnedit/repository/ItemRepository.java
- src/main/java/_team/earnedit/repository/PieceRepository.java
- src/main/java/_team/earnedit/repository/PuzzleSlotRepository.java
- src/main/java/_team/earnedit/service/DailyCheckService.java
- src/main/java/_team/earnedit/service/MainService.java
- src/main/java/_team/earnedit/service/PuzzleService.java
- 도감 정보 조회 API, 조각 정보 조회, 추가 API 등
---
- 스웨거 문서화 
Puzzle
- 도감 정보 조회 API 
- 조각 정보 조회 API 
- 가장 최근 조각 정보 조회 API 
DailyCheck
- 선택한 item을 퍼즐에 등록 API 
MainPage
- 응답객체에 pieceInfo 추가
---
> <img width="1430" height="1134" alt="image" src="https://github.com/user-attachments/assets/5348bc49-1ff5-460a-bec3-52611b7f7180" />
- 사용자의 퍼즐 정보 조회
> <img width="1419" height="1014" alt="image" src="https://github.com/user-attachments/assets/6c2676a4-4c4f-4e1f-80f2-fd897fe93178" />
- 퍼즐의 조각 id로 조회
> <img width="1416" height="905" alt="image" src="https://github.com/user-attachments/assets/2d22bb2c-bf25-4cf6-90aa-286bb7d0c6d5" />
- 가장 최근 획득한 조각 조회 
> <img width="1414" height="1084" alt="image" src="https://github.com/user-attachments/assets/65bfe12f-df76-4704-a743-799ab7217bcf" />
- 출석 체크 시, 지정한 아이템 사용자 퍼즐에 추가 …
> Feat/puzzle 도감 정보 조회 API, 조각 정보 조회, 추가 API 등

- src/main/java/_team/earnedit/dto/wish/WishAddRequest.java
- src/main/java/_team/earnedit/service/MainService.java
- src/main/java/_team/earnedit/service/WishService.java
- (프론트 요청) mainPage, 위시 추가 수정
---
- mainPage 조회 시, piece 정보가 등록되어있지 않을 때 pieceInfo를 null로 응답하도록 수정
- 위시 추가 시, top5 등록 여부를 추가, 5개 초과 시 예외를 던지도록 추가
---
> <img width="1391" height="232" alt="image" src="https://github.com/user-attachments/assets/69e6ad9a-8091-4781-9800-2feb8114e090" />
- 위시 추가 시, Star 5개 초과했을 때 예외 발생
> <img width="1387" height="515" alt="image" src="https://github.com/user-attachments/assets/43524818-25e2-45f1-a921-c33d0bb7f38f" />
- 메인페이지 정보 조회 시, 조각 정보 없으면 null로 응답
---
---
- Swagger UI
---
- 프론트측 요청으로 수정
- 주말이므로 직접 Merge 진행
---
> Ref/mainpage (프론트 요청) mainPage, 위시 추가 수정

- src/main/java/_team/earnedit/controller/StarController.java
- src/main/java/_team/earnedit/dto/star/StarListResponse.java
- src/main/java/_team/earnedit/dto/star/StarOrderUpdateRequest.java
- src/main/java/_team/earnedit/entity/Star.java
- src/main/java/_team/earnedit/global/ErrorCode.java
- src/main/java/_team/earnedit/repository/StarRepository.java
- src/main/java/_team/earnedit/service/StarService.java
- Top5 순서 변경 API 추가
---
- Top5 순서 변경 API 추가
- Star 목록 조회 응답 DTO 변경 (WishListResponse -> StarListResponse)
- 예외 추가 (Star Not Found)
---
> <img width="1466" height="1082" alt="image" src="https://github.com/user-attachments/assets/4838308b-469c-4f6c-8382-16e854bd904e" />
- 현재 wishId 저장된 순서는 41 ~ 45 순서
> <img width="1452" height="1252" alt="image" src="https://github.com/user-attachments/assets/845f5834-90fc-475c-8a14-7455adb86a5a" />
- 순서 변경 API 호출 (45,    44,    42,    41,    43)
> <img width="1304" height="429" alt="image" src="https://github.com/user-attachments/assets/cadf5c44-a55b-4319-84e0-7710afe9296b" />
- (45,    44,    42,    41,    43) 순서로 저장되어 정상적으로 호출 완료
---
---
- Swagger UI
---
- 
---
> Feat/star-order-save Top5 순서 변경 API 

- build.gradle
- src/main/java/_team/earnedit/config/QueryDslConfig.java
- src/main/java/_team/earnedit/controller/WishController.java
- src/main/java/_team/earnedit/dto/PagedResponse.java
- src/main/java/_team/earnedit/dto/wish/WishSearchCondition.java
- src/main/java/_team/earnedit/global/ErrorCode.java
- src/main/java/_team/earnedit/repository/WishRepository.java
- src/main/java/_team/earnedit/service/WishService.java
- 위시 검색 및 필터링 API 
---
- 위시 검색 및 필터링 API
- QueryDsl 설정 및 의존성 추가
---
> <img width="839" height="418" alt="image" src="https://github.com/user-attachments/assets/64630cd9-1c4b-4120-85dd-56652ca848f3" />
- 위시 전체 조회 결과 (2개)
> <img width="1408" height="1106" alt="image" src="https://github.com/user-attachments/assets/25e06f34-8eff-4cfd-9224-c68820e08d5a" />
- 검색어 "청바지" 조회 결과 x 예외 처리
> <img width="1416" height="1317" alt="image" src="https://github.com/user-attachments/assets/c823b866-4db7-45f4-9570-0c84896ea510" />
- "아이폰" 검색, isBought = true 결과, 1개 조회
> <img width="1416" height="1317" alt="image" src="https://github.com/user-attachments/assets/7f6912c4-2b6a-4814-8d6a-bfd20f0e63d6" />
- "아이폰" 검색, isBought = false 결과, 예외 처리
> <img width="1413" height="1329" alt="image" …
> Feat/search-wish 위시 검색 및 필터링 API 

- src/main/java/_team/earnedit/controller/admin/ItemAdminController.java
- src/main/java/_team/earnedit/controller/admin/PuzzleSlotAdminController.java
- src/main/java/_team/earnedit/dto/item/ItemRequest.java
- src/main/java/_team/earnedit/entity/Item.java
- src/main/java/_team/earnedit/repository/PuzzleSlotRepository.java
- src/main/java/_team/earnedit/service/admin/item/ItemServiceImpl.java
- src/main/resources/templates/admin/item-form.html
- src/main/resources/templates/admin/item-list.html
- src/main/resources/templates/admin/puzzle-slot-list.html
- 테마별 필터링 기능 추가, Item.theme -> Item.category로 수정
---
- 테마별 필터링 기능 추가
- Item 도메인의 theme를 category 로 수정(아이템 도메인에 부적합하다는 생각이 듦)
---
> <img width="1277" height="614" alt="image" src="https://github.com/user-attachments/assets/47c060b9-7895-4b00-b2b2-acb7c9e94603" />
- 상단에 필터링 UI 추가
> <img width="1381" height="482" alt="image" src="https://github.com/user-attachments/assets/f21fe577-d789-4b58-87cd-786e8cc871f2" />
- 필터링 적용 시, 해당 테마 제품만 조회 가능
> <img width="679" height="774" alt="image" src="https://github.com/user-attachments/assets/2437c613-2ee4-4b80-8246-5f34c6a2a79d" />
- 물품 등록 시, 테마 선택 -> 카테고리 수기 입력으로 수정
---
---
- 로컬 테스트
- Item DB를 밀고 데이터 재삽입
---
- Item 도메인에 엮여있을 필요가 없는 컬럼이라고 생각해서 Theme를 category로 수정하였습니다.
- 
---
> Ref/admin 테마별 필터링 기능 추가, Item.theme -> Item.category로 수정

- src/main/java/_team/earnedit/entity/User.java
- src/main/java/_team/earnedit/global/scheduler/CheckInResetScheduler.java
- src/main/java/_team/earnedit/repository/UserRepository.java
- User 엔티티에 출석체크 컬럼추가, CheckInResetScheduler 구현
---
- User 엔티티에 출석체크 컬럼추가
- CheckInResetScheduler 구현
- 쿼리메서드로 매일밤 자정에 전체유저 출석체크여부 false로 reset
---
> 
---
---
---
- 서버 db에 컬럼추가완료
---
> Feat/colum : User 엔티티에 출석체크 컬럼추가, CheckInResetScheduler 구현

- src/main/java/_team/earnedit/repository/UserRepository.java
- src/main/java/_team/earnedit/service/PasswordResetService.java
- 비밀번호찾기 기능에서 local로 가입된 계정만 처리
---
`flutter: {"code":"DB_ACCESS_ERROR","message":"데이터베이스 오류 발생: Query did not return a unique result: 2 results were returned"}`
- 해당 오류 수정
---
---
---
---
---
> fix : 비밀번호찾기 기능에서 local로 가입된 계정만 처리

- src/main/java/_team/earnedit/controller/PuzzleController.java
- src/main/java/_team/earnedit/dto/puzzle/PuzzleResponse.java
- src/main/java/_team/earnedit/dto/term/TermRequestDto.java
- src/main/java/_team/earnedit/service/DailyCheckService.java
- src/main/java/_team/earnedit/service/PuzzleService.java
- 퍼즐 정보 조회 API 버그 수정, 조각 중복 추가 버그 수정
---
- 퍼즐 정보 조회 API 버그 수정
- 조각 중복 추가 버그 수정
- puzzleInfo 데이터에 퍼즐 요약 정보 json 추가
- TermRequestDto에서 약관유형 example 값 수정 (스웨거 회원가입 테스트 시, 미작동 했음)
- PuzzleResponse에 pieceId 응답을 추가
---
> <img width="1342" height="413" alt="image" src="https://github.com/user-attachments/assets/965a42ea-7d72-4015-ad61-cf31db1baa54" />
- /api/puzzle (GET) 요청 시, pieceId를 포함하여 응답
> <img width="1082" height="390" alt="image" src="https://github.com/user-attachments/assets/a595db0b-56bb-4806-a7db-1183ab0daadf" />
- 이미 추가한 조각 보상으로 선택하게 될 때, 중복 추가 방지 예외 던짐
---
---
- Swagger UI
---
---
> Bug/puzzle 퍼즐 정보 조회 API 버그 수정, 조각 중복 추가 버그 수정

- src/main/java/_team/earnedit/config/security/CustomAccessDeniedHandler.java
- src/main/java/_team/earnedit/config/security/JwtFilterConfig.java
- src/main/java/_team/earnedit/config/security/SecurityConfig.java
- src/main/java/_team/earnedit/controller/FileUploadController.java
- src/main/java/_team/earnedit/global/jwt/JwtAuthFilter.java
- src/main/java/_team/earnedit/global/jwt/JwtUtil.java
- src/main/java/_team/earnedit/service/AuthService.java
- JWT 인증/인가 구조 전면 정비
---
-JWT 기반 인증 필터를 전면 개선, 인가 규칙을 엔드포인트별로 명시
- 로그아웃 토큰 블랙리스트가 필터 레벨에서 선차단되며, 만료/무효 토큰은 일관된 JSON으로 즉시 401 응답
- /admin/**는 기존대로 임시 올 허용
- 나중에 별도 관리자 보안을 설계 예정
- Flutter 앱 기준으로 CORS 의존 제거(기존 CorsConfig는 유지)
- 운영 안전성/가시성 향상을 위한 보안 헤더(HSTS/CSP 등) 적용
---
> 기존 로그인 -> 진입 good (인증필요 x)
> 발급 토큰으로 인증필요 api 호출 -> 진입 good
> 발급 토큰으로 로그아웃 처리 -> 진입 good
> 로그아웃된 계정의 토큰으로 api 호출 -> 블랙리스트 처리된 토큰이므로 접근x
> 로그아웃된 계정의 refresh 토큰으로 refresh api 호출 -> 마찬가지로 접근x, 발급 불가
> 같은 계정 재로그인 후, 새로운 토큰으로 refresh -> 잘 작동
---
---
---
---
> Ref/security : JWT 인증/인가 구조 전면 정비 (+블랙리스트/헤더강화/엔드포인트 정리)

- src/main/java/_team/earnedit/controller/ProfileController.java
- src/main/java/_team/earnedit/controller/ReportController.java
- src/main/java/_team/earnedit/dto/profile/UpdateVisibilityRequestDto.java
- src/main/java/_team/earnedit/dto/report/ReportUserRequestDto.java
- src/main/java/_team/earnedit/entity/ReportReason.java
- src/main/java/_team/earnedit/entity/User.java
- src/main/java/_team/earnedit/entity/UserReport.java
- src/main/java/_team/earnedit/global/ErrorCode.java
- src/main/java/_team/earnedit/global/exception/report/ReportException.java
- src/main/java/_team/earnedit/repository/ReportReasonRepository.java
- src/main/java/_team/earnedit/repository/UserReportRepository.java
- src/main/java/_team/earnedit/service/ProfileService.java
- src/main/java/_team/earnedit/service/ReportService.java
- 공개범위 전환 api, 타유저신고api (신고남용방지 로직)
---
- Entity, 각 repository 추가
- Report_Reason
- User_Report
- Report 기능 관련 파일 추가
- service, controller, custom exception, dtos ...
- reportUser 서비스 / 컨트롤러 메서드 구현
- 2단계 신고남용 방지 -> 예외처리
- updateVisibility 서비스 / 컨트롤러 메서드 구현
- User 엔티티에 update 도메인메서드 설정 후 이용
---
> 공개범위 전환 api
> 타유저 신고 api : 성공
> 타유저 신고 api : 예외 예시 1
> 타유저 신고 api : 예외 예시 2
> 신고이유 테이블
---
---
---
- 머지 이후 db에 신고사유-코드 넣어줘야 이용 가능함
---
> Feat/report : 공개범위 전환 api, 타유저신고api (신고남용방지 로직)

- src/main/java/_team/earnedit/controller/ProductController.java
- src/main/java/_team/earnedit/dto/item/NaverProductSearchRequest.java
- src/main/java/_team/earnedit/dto/main/MainPageResponse.java
- src/main/java/_team/earnedit/entity/User.java
- src/main/java/_team/earnedit/mapper/MainPageMapper.java
- src/main/java/_team/earnedit/repository/PuzzleSlotRepository.java
- src/main/java/_team/earnedit/repository/SearchItemRepository.java
- src/main/java/_team/earnedit/service/DailyCheckService.java
- src/main/java/_team/earnedit/service/NaverShoppingService.java
- src/main/java/_team/earnedit/service/ProductService.java
- src/main/java/_team/earnedit/service/RewardCheckInService.java
- 상품 검색 API 복구 및 API 요청 형식 변경 및 준영님 요청사항 처리
---
- 상품 검색 API 복구 및 API 요청 형식 변경
- @ModelAttribute -> @RequestParam 변경
- 배포 서버 측 .env 업데이트(naverShopping API 관련 환경변수 추가)
- 메인페이지 정보 조회 시, 유저의 isPublic 필드 응답 추가
- 출석 점수 지급 로직이 트랜잭션에 묶여 예외 발생 시 보상 지급 안되는 버그 수정
---
> <img width="1530" height="1461" alt="image" src="https://github.com/user-attachments/assets/dd86fdda-ad69-4682-b904-5b6d4effbe12" />
- 상품 검색 API 로컬에서 정상 동작 확인
> <img width="1534" height="1149" alt="image" src="https://github.com/user-attachments/assets/4cb73386-6e99-4260-93cb-083f74f676e6" />
- 메인페이지 정보 조회 시, 유저의 isPublic 필드 응답 추가
---
---
- Swagger UI
---
---
> bug : 상품 검색 API 복구 및 API 요청 형식 변경

- src/main/java/_team/earnedit/service/RankService.java
- 2글자 닉네임 랭크 페이지에서 동* 과 같이 나타내도록 수정
---
- 2글자 닉네임 랭크 페이지에서 동* 과 같이 나타내도록 수정
---
> <img width="1323" height="452" alt="image" src="https://github.com/user-attachments/assets/a2dce486-6493-4009-851f-b85b0f9d93b5" />
- 비공개 처리
---
---
- Swagger UI
---
---
> ref: 2글자 닉네임 랭크 페이지에서 동* 과 같이 나타내도록 수정
